apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  selector:
    matchLabels:
      app: redis-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-pod
    spec:
      containers:
        - name: redis-deployment-cnt-1
          image: redis
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 6379
        - name: redis-deployment-busybox
          image: busybox
          command:
            - sleep
            - "30"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
