apiVersion: v1
kind: PersistentVolume
metadata:
  name: disk-1.2-1gb
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: db-disk
  local:
    path: /mnt/disk-1/2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - "minikube"
