apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-1gb
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: db-disk
  accessModes:
    - ReadWriteOnce
